name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone for better analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Upgrade Gradle Wrapper
        run: |
          rm -rf gradlew gradlew.bat gradle
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip -O gradle.zip
          unzip gradle.zip
          mv gradle-7.6 gradle
          chmod +x gradle/bin/gradle

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Delete Old Gradle Cache (Fix Gradle 2.4 Issue)
        run: |
          rm -rf ~/.gradle/wrapper/dists/gradle-2.4-all

      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradle/bin/gradle wrapper --gradle-version 7.6 --distribution-type all
          ./gradlew clean build sonar --info
